//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBlech.TextToolbox.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BillBlech.TextToolbox.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns percentage of words found in text.
        /// </summary>
        public static string CountWordsInText_Description {
            get {
                return ResourceManager.GetString("CountWordsInText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Words in Text.
        /// </summary>
        public static string CountWordsInText_DisplayName {
            get {
                return ResourceManager.GetString("CountWordsInText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of words found in text.
        /// </summary>
        public static string CountWordsInText_Percentage_Description {
            get {
                return ResourceManager.GetString("CountWordsInText_Percentage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string CountWordsInText_Percentage_DisplayName {
            get {
                return ResourceManager.GetString("CountWordsInText_Percentage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words to be searched (Collection of Strings).
        /// </summary>
        public static string CountWordsInText_SearchWords_Description {
            get {
                return ResourceManager.GetString("CountWordsInText_SearchWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Words.
        /// </summary>
        public static string CountWordsInText_SearchWords_DisplayName {
            get {
                return ResourceManager.GetString("CountWordsInText_SearchWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted the value encrypted by the robot.
        /// </summary>
        public static string DecryptValue_Description {
            get {
                return ResourceManager.GetString("DecryptValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt Value.
        /// </summary>
        public static string DecryptValue_DisplayName {
            get {
                return ResourceManager.GetString("DecryptValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt the value encrypted by the robot.
        /// </summary>
        public static string DecryptValue_EncryptedText_Description {
            get {
                return ResourceManager.GetString("DecryptValue_EncryptedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Text.
        /// </summary>
        public static string DecryptValue_EncryptedText_DisplayName {
            get {
                return ResourceManager.GetString("DecryptValue_EncryptedText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Encryption algorithm to be appplied.
        /// </summary>
        public static string DecryptValue_EncryptionAlgorithm_Description {
            get {
                return ResourceManager.GetString("DecryptValue_EncryptionAlgorithm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption algorithm.
        /// </summary>
        public static string DecryptValue_EncryptionAlgorithm_DisplayName {
            get {
                return ResourceManager.GetString("DecryptValue_EncryptionAlgorithm_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted value by the robot.
        /// </summary>
        public static string DecryptValue_PlainText_Description {
            get {
                return ResourceManager.GetString("DecryptValue_PlainText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        public static string DecryptValue_PlainText_DisplayName {
            get {
                return ResourceManager.GetString("DecryptValue_PlainText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Config File for this activity, it is available in the Project URL, section Resources.
        /// </summary>
        public static string DetectLanguage_ConfigFile_Description {
            get {
                return ResourceManager.GetString("DetectLanguage_ConfigFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config File.
        /// </summary>
        public static string DetectLanguage_ConfigFile_DisplayName {
            get {
                return ResourceManager.GetString("DetectLanguage_ConfigFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language detection using https://github.com/ivanakcheurov/ntextcat.
        /// </summary>
        public static string DetectLanguage_Description {
            get {
                return ResourceManager.GetString("DetectLanguage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Language.
        /// </summary>
        public static string DetectLanguage_DisplayName {
            get {
                return ResourceManager.GetString("DetectLanguage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be classified.
        /// </summary>
        public static string DetectLanguage_InputText_Description {
            get {
                return ResourceManager.GetString("DetectLanguage_InputText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        public static string DetectLanguage_InputText_DisplayName {
            get {
                return ResourceManager.GetString("DetectLanguage_InputText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language for the Input Text.
        /// </summary>
        public static string DetectLanguage_Language_Description {
            get {
                return ResourceManager.GetString("DetectLanguage_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string DetectLanguage_Language_DisplayName {
            get {
                return ResourceManager.GetString("DetectLanguage_Language_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentiment Analysis using https://text-processing.com/docs/sentiment.html (english, french or dutch languages only).
        /// </summary>
        public static string DetectSentiment_Description {
            get {
                return ResourceManager.GetString("DetectSentiment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Sentiment.
        /// </summary>
        public static string DetectSentiment_DisplayName {
            get {
                return ResourceManager.GetString("DetectSentiment_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be analysed.
        /// </summary>
        public static string DetectSentiment_InputText_Description {
            get {
                return ResourceManager.GetString("DetectSentiment_InputText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        public static string DetectSentiment_InputText_DisplayName {
            get {
                return ResourceManager.GetString("DetectSentiment_InputText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns &apos;neg&apos;, &apos;neutral&apos; or &apos;pos&apos;.
        /// </summary>
        public static string DetectSentiment_SentimentAnalysis_Description {
            get {
                return ResourceManager.GetString("DetectSentiment_SentimentAnalysis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentiment Analysis.
        /// </summary>
        public static string DetectSentiment_SentimentAnalysis_DisplayName {
            get {
                return ResourceManager.GetString("DetectSentiment_SentimentAnalysis_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt the value so that only the robot can decrypt it.
        /// </summary>
        public static string EncryptValue_Description {
            get {
                return ResourceManager.GetString("EncryptValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt Value.
        /// </summary>
        public static string EncryptValue_DisplayName {
            get {
                return ResourceManager.GetString("EncryptValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value that can be read only by the robot.
        /// </summary>
        public static string EncryptValue_EncryptedText_Description {
            get {
                return ResourceManager.GetString("EncryptValue_EncryptedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Text.
        /// </summary>
        public static string EncryptValue_EncryptedText_DisplayName {
            get {
                return ResourceManager.GetString("EncryptValue_EncryptedText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Encryption algorithm to be appplied.
        /// </summary>
        public static string EncryptValue_EncryptionAlgorithm_Description {
            get {
                return ResourceManager.GetString("EncryptValue_EncryptionAlgorithm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption algorithm.
        /// </summary>
        public static string EncryptValue_EncryptionAlgorithm_DisplayName {
            get {
                return ResourceManager.GetString("EncryptValue_EncryptionAlgorithm_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be encrypted.
        /// </summary>
        public static string EncryptValue_PlainText_Description {
            get {
                return ResourceManager.GetString("EncryptValue_PlainText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        public static string EncryptValue_PlainText_DisplayName {
            get {
                return ResourceManager.GetString("EncryptValue_PlainText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words to be searched in Input Text (Collection of Strings).
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_AnchorWords_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_AnchorWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words.
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_AnchorWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_AnchorWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all text until next letter character is found.
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_DisplayLog_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text Until Next Letter.
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex Expression.
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_DisplayRegex_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_DisplayRegex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex.
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_DisplayRegex_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_DisplayRegex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Resutls (Array of Strings).
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_Results_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ExtractAllCharactersUntilNextLetter_Results_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilNextLetter_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words to be searched in Input Text (Collection of Strings).
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_AnchorWords_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_AnchorWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words.
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_AnchorWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_AnchorWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Single Word Next to Anchor Text.
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_DisplayLog_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text Until White Space.
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex Expression.
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_DisplayRegex_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_DisplayRegex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex.
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_DisplayRegex_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_DisplayRegex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results (Array of Strings).
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_Results_Description {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ExtractAllCharactersUntilWhiteSpace_Results_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllCharactersUntilWhiteSpace_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words to be searched in Input Text (Collection of Strings).
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_AnchorText_Description {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_AnchorText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_AnchorText_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_AnchorText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Word or All the Words to be found in Input Text.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_AnchorTextParam_Description {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_AnchorTextParam_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words Parameter.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_AnchorTextParam_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_AnchorTextParam_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all text below anchor text until the end of Input Text.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_Description {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_DisplayLog_Description {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract All Lines Below Anchor Words.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex expression.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_DisplayRegex_Description {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_DisplayRegex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_DisplayRegex_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_DisplayRegex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results (Array of Strings).
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_Results_Description {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ExtractAllLinesBelowAnchorText_Results_DisplayName {
            get {
                return ResourceManager.GetString("ExtractAllLinesBelowAnchorText_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words to be searched in Input Text (Collection of Strings).
        /// </summary>
        public static string ExtractTextAboveAnchorWords_AnchorWords_Description {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_AnchorWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_AnchorWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_AnchorWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text above a specific Anchor Word.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_Description {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_DisplayLog_Description {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text Above Anchor Words.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex Expression.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_DisplayRegex_Description {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_DisplayRegex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_DisplayRegex_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_DisplayRegex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines above archor row to be extracted.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_LinesNumber_Description {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_LinesNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines Above.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_LinesNumber_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_LinesNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lines to be extracted.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_NumberLines_Description {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_NumberLines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Lines.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_NumberLines_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_NumberLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results (Array of Strings).
        /// </summary>
        public static string ExtractTextAboveAnchorWords_Results_Description {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ExtractTextAboveAnchorWords_Results_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextAboveAnchorWords_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words to be searched in Input Text (Collection of Strings).
        /// </summary>
        public static string ExtractTextBelowAnchorWords_AnchorWords_Description {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_AnchorWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_AnchorWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_AnchorWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text below a specific Anchor Word.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_Description {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_DisplayLog_Description {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text Below Anchor Words.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex Expression.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_DisplayRegex_Description {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_DisplayRegex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_DisplayRegex_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_DisplayRegex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines below anchor row to be extracted.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_LinesNumber_Description {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_LinesNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines Below.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_LinesNumber_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_LinesNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lines to be extracted.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_NumberLines_Description {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_NumberLines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Lines.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_NumberLines_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_NumberLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results (Array of Strings).
        /// </summary>
        public static string ExtractTextBelowAnchorWords_Results_Description {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ExtractTextBelowAnchorWords_Results_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBelowAnchorWords_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beggining words to be searched (Collection of Strings).
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_BegWords_Description {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_BegWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beg Words.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_BegWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_BegWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract all text between two anchor words.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_Description {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex Expression.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_DisplatyRegex_Description {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_DisplatyRegex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_DisplatyRegex_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_DisplatyRegex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_DisplayLog_Description {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text Between Two Anchor Words.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending words to be searched (Collection of Strings), leave it null in case it is the end of the row.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_EndWords_Description {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_EndWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Words.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_EndWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_EndWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both words in samme or different lines.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_RegexParameter_Description {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_RegexParameter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Parameter.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_RegexParameter_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_RegexParameter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results (Array of Strings).
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_Results_Description {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ExtractTextBetweenTwoAnchorWords_Results_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextBetweenTwoAnchorWords_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words to be searched in Input Text (Collection of Strings).
        /// </summary>
        public static string ExtractTextUntilBlankLine_AnchorWords_Description {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_AnchorWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words.
        /// </summary>
        public static string ExtractTextUntilBlankLine_AnchorWords_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_AnchorWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Word or all the Words to be found in Input Text.
        /// </summary>
        public static string ExtractTextUntilBlankLine_AnchorWordsParameter_Description {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_AnchorWordsParameter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Words Parameter.
        /// </summary>
        public static string ExtractTextUntilBlankLine_AnchorWordsParameter_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_AnchorWordsParameter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text Above or Below Anchor Word(s) until Blank Line is Found.
        /// </summary>
        public static string ExtractTextUntilBlankLine_Description {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above / Below Anchor Words.
        /// </summary>
        public static string ExtractTextUntilBlankLine_Direction_Description {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_Direction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string ExtractTextUntilBlankLine_Direction_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_Direction_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string ExtractTextUntilBlankLine_DisplayLog_Description {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string ExtractTextUntilBlankLine_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text Until Blank Line.
        /// </summary>
        public static string ExtractTextUntilBlankLine_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex Expression.
        /// </summary>
        public static string ExtractTextUntilBlankLine_DisplayRegex_Description {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_DisplayRegex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex.
        /// </summary>
        public static string ExtractTextUntilBlankLine_DisplayRegex_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_DisplayRegex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Anchor Word row info in the output? (Boolean Variable).
        /// </summary>
        public static string ExtractTextUntilBlankLine_IncludeAnchorWordsRow_Description {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_IncludeAnchorWordsRow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Anchor Words Row.
        /// </summary>
        public static string ExtractTextUntilBlankLine_IncludeAnchorWordsRow_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_IncludeAnchorWordsRow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results (Array of Strings).
        /// </summary>
        public static string ExtractTextUntilBlankLine_Results_Description {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ExtractTextUntilBlankLine_Results_DisplayName {
            get {
                return ResourceManager.GetString("ExtractTextUntilBlankLine_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Word or All the Words to be found in Array Item.
        /// </summary>
        public static string FindArrayItems_AnchorWordsParameters_Description {
            get {
                return ResourceManager.GetString("FindArrayItems_AnchorWordsParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Words Parameter.
        /// </summary>
        public static string FindArrayItems_AnchorWordsParameters_DisplayName {
            get {
                return ResourceManager.GetString("FindArrayItems_AnchorWordsParameters_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Array items using Filter Words (Collection of Strings).
        /// </summary>
        public static string FindArrayItems_Description {
            get {
                return ResourceManager.GetString("FindArrayItems_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string FindArrayItems_DisplayLog_Description {
            get {
                return ResourceManager.GetString("FindArrayItems_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string FindArrayItems_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("FindArrayItems_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Array Items.
        /// </summary>
        public static string FindArrayItems_DisplayName {
            get {
                return ResourceManager.GetString("FindArrayItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex Expression.
        /// </summary>
        public static string FindArrayItems_DisplayRegex_Description {
            get {
                return ResourceManager.GetString("FindArrayItems_DisplayRegex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Regex.
        /// </summary>
        public static string FindArrayItems_DisplayRegex_DisplayName {
            get {
                return ResourceManager.GetString("FindArrayItems_DisplayRegex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words to be searched in the Input Array (Collection of Strings).
        /// </summary>
        public static string FindArrayItems_FilterWords_Description {
            get {
                return ResourceManager.GetString("FindArrayItems_FilterWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Words.
        /// </summary>
        public static string FindArrayItems_FilterWords_DisplayName {
            get {
                return ResourceManager.GetString("FindArrayItems_FilterWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array to be Searched (Array of Strings).
        /// </summary>
        public static string FindArrayItems_InputArray_Description {
            get {
                return ResourceManager.GetString("FindArrayItems_InputArray_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Array.
        /// </summary>
        public static string FindArrayItems_InputArray_DisplayName {
            get {
                return ResourceManager.GetString("FindArrayItems_InputArray_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results (Array of Strings).
        /// </summary>
        public static string FindArrayItems_Results_Description {
            get {
                return ResourceManager.GetString("FindArrayItems_Results_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string FindArrayItems_Results_DisplayName {
            get {
                return ResourceManager.GetString("FindArrayItems_Results_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID is used for the Preview Functionalities.
        /// </summary>
        public static string IDText_Description {
            get {
                return ResourceManager.GetString("IDText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string IDText_DisplayName {
            get {
                return ResourceManager.GetString("IDText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if any of the item belongs to an Array of Strings.
        /// </summary>
        public static string MatchItemInArray_Description {
            get {
                return ResourceManager.GetString("MatchItemInArray_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Item in Array.
        /// </summary>
        public static string MatchItemInArray_DisplayName {
            get {
                return ResourceManager.GetString("MatchItemInArray_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array to be Searched (Array of Strings).
        /// </summary>
        public static string MatchItemInArray_InputArray_Description {
            get {
                return ResourceManager.GetString("MatchItemInArray_InputArray_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Array.
        /// </summary>
        public static string MatchItemInArray_InputArray_DisplayName {
            get {
                return ResourceManager.GetString("MatchItemInArray_InputArray_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return if item was found in the Array (Boolean Variable).
        /// </summary>
        public static string MatchItemInArray_IsFound_Description {
            get {
                return ResourceManager.GetString("MatchItemInArray_IsFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Found.
        /// </summary>
        public static string MatchItemInArray_IsFound_DisplayName {
            get {
                return ResourceManager.GetString("MatchItemInArray_IsFound_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words to be searched in the Input Array (Collection of Strings).
        /// </summary>
        public static string MatchItemInArray_SearchWord_Description {
            get {
                return ResourceManager.GetString("MatchItemInArray_SearchWord_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Words.
        /// </summary>
        public static string MatchItemInArray_SearchWord_DisplayName {
            get {
                return ResourceManager.GetString("MatchItemInArray_SearchWord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extracted text from the text file.
        /// </summary>
        public static string ReadTextFileEncondig_Content_Description {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_Content_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ReadTextFileEncondig_Content_DisplayName {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_Content_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read text file with encoding option.
        /// </summary>
        public static string ReadTextFileEncondig_Description {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string ReadTextFileEncondig_DisplayLog_Description {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string ReadTextFileEncondig_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Text File Encondig.
        /// </summary>
        public static string ReadTextFileEncondig_DisplayName {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding option to be used.
        /// </summary>
        public static string ReadTextFileEncondig_Encoding_Description {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_Encoding_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string ReadTextFileEncondig_Encoding_DisplayName {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_Encoding_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path to be read.
        /// </summary>
        public static string ReadTextFileEncondig_FileName_Description {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_FileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string ReadTextFileEncondig_FileName_DisplayName {
            get {
                return ResourceManager.GetString("ReadTextFileEncondig_FileName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Text.
        /// </summary>
        public static string RemoveEmptyRows_AdjustedTextRow_Description {
            get {
                return ResourceManager.GetString("RemoveEmptyRows_AdjustedTextRow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Text.
        /// </summary>
        public static string RemoveEmptyRows_AdjustedTextRow_DisplayName {
            get {
                return ResourceManager.GetString("RemoveEmptyRows_AdjustedTextRow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Empty Rows from String.
        /// </summary>
        public static string RemoveEmptyRows_Description {
            get {
                return ResourceManager.GetString("RemoveEmptyRows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Empty Rows.
        /// </summary>
        public static string RemoveEmptyRows_DisplayName {
            get {
                return ResourceManager.GetString("RemoveEmptyRows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be adjusted.
        /// </summary>
        public static string RemoveEmptyRows_InputTextRow_Description {
            get {
                return ResourceManager.GetString("RemoveEmptyRows_InputTextRow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        public static string RemoveEmptyRows_InputTextRow_DisplayName {
            get {
                return ResourceManager.GetString("RemoveEmptyRows_InputTextRow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text withou requested words removed.
        /// </summary>
        public static string RemoveWords_AdjustText_Description {
            get {
                return ResourceManager.GetString("RemoveWords_AdjustText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Text.
        /// </summary>
        public static string RemoveWords_AdjustText_DisplayName {
            get {
                return ResourceManager.GetString("RemoveWords_AdjustText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Specific Words from Input Text.
        /// </summary>
        public static string RemoveWords_Description {
            get {
                return ResourceManager.GetString("RemoveWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string RemoveWords_DisplayLog_Description {
            get {
                return ResourceManager.GetString("RemoveWords_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string RemoveWords_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("RemoveWords_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Words.
        /// </summary>
        public static string RemoveWords_DisplayName {
            get {
                return ResourceManager.GetString("RemoveWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for Custom Occurrence only.
        /// </summary>
        public static string RemoveWords_OccurrenceNumber_Description {
            get {
                return ResourceManager.GetString("RemoveWords_OccurrenceNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurrence Position.
        /// </summary>
        public static string RemoveWords_OccurrenceNumber_DisplayName {
            get {
                return ResourceManager.GetString("RemoveWords_OccurrenceNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All, First, Last or Custom Occurrence.
        /// </summary>
        public static string RemoveWords_Occurrences_Description {
            get {
                return ResourceManager.GetString("RemoveWords_Occurrences_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurrence Parameter.
        /// </summary>
        public static string RemoveWords_Occurrences_DisplayName {
            get {
                return ResourceManager.GetString("RemoveWords_Occurrences_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words to be removed from input text (Collection of Strings).
        /// </summary>
        public static string RemoveWords_Words_Description {
            get {
                return ResourceManager.GetString("RemoveWords_Words_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        public static string RemoveWords_Words_DisplayName {
            get {
                return ResourceManager.GetString("RemoveWords_Words_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text after replaced words.
        /// </summary>
        public static string ReplaceWords_AdjustedText_Description {
            get {
                return ResourceManager.GetString("ReplaceWords_AdjustedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Text.
        /// </summary>
        public static string ReplaceWords_AdjustedText_DisplayName {
            get {
                return ResourceManager.GetString("ReplaceWords_AdjustedText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Specific Words from Input Text.
        /// </summary>
        public static string ReplaceWords_Description {
            get {
                return ResourceManager.GetString("ReplaceWords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Activity Output in the Ouput Pane.
        /// </summary>
        public static string ReplaceWords_DisplayLog_Description {
            get {
                return ResourceManager.GetString("ReplaceWords_DisplayLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Log.
        /// </summary>
        public static string ReplaceWords_DisplayLog_DisplayName {
            get {
                return ResourceManager.GetString("ReplaceWords_DisplayLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Words.
        /// </summary>
        public static string ReplaceWords_DisplayName {
            get {
                return ResourceManager.GetString("ReplaceWords_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Custom Occurance Only.
        /// </summary>
        public static string ReplaceWords_IndexOccurence_Description {
            get {
                return ResourceManager.GetString("ReplaceWords_IndexOccurence_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurence Position.
        /// </summary>
        public static string ReplaceWords_IndexOccurence_DisplayName {
            get {
                return ResourceManager.GetString("ReplaceWords_IndexOccurence_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Word.
        /// </summary>
        public static string ReplaceWords_ReplacedWord_Description {
            get {
                return ResourceManager.GetString("ReplaceWords_ReplacedWord_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced Word.
        /// </summary>
        public static string ReplaceWords_ReplacedWord_DisplayName {
            get {
                return ResourceManager.GetString("ReplaceWords_ReplacedWord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words to be replaced (Collection of Strings).
        /// </summary>
        public static string ReplaceWords_SearchWord_Description {
            get {
                return ResourceManager.GetString("ReplaceWords_SearchWord_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Words.
        /// </summary>
        public static string ReplaceWords_SearchWord_DisplayName {
            get {
                return ResourceManager.GetString("ReplaceWords_SearchWord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace First, Last, All or Custom Occurance.
        /// </summary>
        public static string ReplaceWords_TextOccurrance_Description {
            get {
                return ResourceManager.GetString("ReplaceWords_TextOccurrance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurence Parameter.
        /// </summary>
        public static string ReplaceWords_TextOccurrance_DisplayName {
            get {
                return ResourceManager.GetString("ReplaceWords_TextOccurrance_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an array of strings with pieces of text parts.
        /// </summary>
        public static string SplitTextByBlankLines_Description {
            get {
                return ResourceManager.GetString("SplitTextByBlankLines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Text By Blank Lines.
        /// </summary>
        public static string SplitTextByBlankLines_DisplayName {
            get {
                return ResourceManager.GetString("SplitTextByBlankLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces of text separated by blank lines (Array of strings).
        /// </summary>
        public static string SplitTextByBlankLines_PiecesOfText_Description {
            get {
                return ResourceManager.GetString("SplitTextByBlankLines_PiecesOfText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces of Text.
        /// </summary>
        public static string SplitTextByBlankLines_PiecesOfText_DisplayName {
            get {
                return ResourceManager.GetString("SplitTextByBlankLines_PiecesOfText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Text by New Lines.
        /// </summary>
        public static string SplitTextNewLines_Description {
            get {
                return ResourceManager.GetString("SplitTextNewLines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Text New Lines.
        /// </summary>
        public static string SplitTextNewLines_DisplayName {
            get {
                return ResourceManager.GetString("SplitTextNewLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of strings each item containing a line.
        /// </summary>
        public static string SplitTextNewLines_TextLines_Description {
            get {
                return ResourceManager.GetString("SplitTextNewLines_TextLines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Lines.
        /// </summary>
        public static string SplitTextNewLines_TextLines_DisplayName {
            get {
                return ResourceManager.GetString("SplitTextNewLines_TextLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Text into an Array with uneven blank spaces.
        /// </summary>
        public static string SplitTextRows_Description {
            get {
                return ResourceManager.GetString("SplitTextRows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Text Uneven Blank Spaces.
        /// </summary>
        public static string SplitTextRows_DisplayName {
            get {
                return ResourceManager.GetString("SplitTextRows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Words (Array of Strings).
        /// </summary>
        public static string SplitTextRows_ExtractedText_Description {
            get {
                return ResourceManager.GetString("SplitTextRows_ExtractedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Words.
        /// </summary>
        public static string SplitTextRows_ExtractedText_DisplayName {
            get {
                return ResourceManager.GetString("SplitTextRows_ExtractedText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be splited.
        /// </summary>
        public static string SplitTextRows_InputTextRow_Description {
            get {
                return ResourceManager.GetString("SplitTextRows_InputTextRow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text Row.
        /// </summary>
        public static string SplitTextRows_InputTextRow_DisplayName {
            get {
                return ResourceManager.GetString("SplitTextRows_InputTextRow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of empty Characters to be considered as space among words.
        /// </summary>
        public static string SplitTextRows_NullLimit_Description {
            get {
                return ResourceManager.GetString("SplitTextRows_NullLimit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Limit.
        /// </summary>
        public static string SplitTextRows_NullLimit_DisplayName {
            get {
                return ResourceManager.GetString("SplitTextRows_NullLimit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress Null Values (Boolen Variable).
        /// </summary>
        public static string SuppressNulls_Description {
            get {
                return ResourceManager.GetString("SuppressNulls_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Empty words from extracted text.
        /// </summary>
        public static string SuppressNulls_DisplayName {
            get {
                return ResourceManager.GetString("SuppressNulls_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a Text for Text Activities.
        /// </summary>
        public static string TextApplicationScope_Description {
            get {
                return ResourceManager.GetString("TextApplicationScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Application Scope.
        /// </summary>
        public static string TextApplicationScope_DisplayName {
            get {
                return ResourceManager.GetString("TextApplicationScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template File for Preview Functionalities.
        /// </summary>
        public static string TextApplicationScope_FilePathPreview_Description {
            get {
                return ResourceManager.GetString("TextApplicationScope_FilePathPreview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path for Preview.
        /// </summary>
        public static string TextApplicationScope_FilePathPreview_DisplayName {
            get {
                return ResourceManager.GetString("TextApplicationScope_FilePathPreview_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Text to be processed.
        /// </summary>
        public static string TextApplicationScope_InputText_Description {
            get {
                return ResourceManager.GetString("TextApplicationScope_InputText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        public static string TextApplicationScope_InputText_DisplayName {
            get {
                return ResourceManager.GetString("TextApplicationScope_InputText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
